services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_api
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      OLLAMA_HOST: "http://ollama:11434"
      DATABASE_URL: "postgresql+psycopg2://raguser:ragpass@db:5432/ragobs"
      ENV: "DEV"
      HF_HOME: "/app/.hf-cache"
      SENTENCE_TRANSFORMERS_HOME: "/app/.hf-cache"
      TRANSFORMERS_CACHE: "/app/.hf-cache/transformers"
      HF_HUB_OFFLINE: "1"
      TRANSFORMERS_OFFLINE: "1"
      FLASHCARD_LLM_MODEL: "llama3.1"
      FLASHCARD_LLM_TIMEOUT_SECONDS: "120"
      FLASHCARD_LLM_KEEP_ALIVE: "30m"
      FLASHCARD_MAX_TOKENS_PER_CARD: "110"
      FLASHCARD_LLM_MAX_TOKENS: "1800"

    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    depends_on:
      - db
      - ollama
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      SERVER_URL: "http://localhost:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ragobs
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
  ollama:
